# Site settings
title: Caustic Laseretag System
email: AlexeyABulatov@yandex.ru
description: |
  Система для игры в лазертаг с открытым исходным кодом и широкими возможностями.
  Сайт собран c использованием Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ltcaustic.org" # the base hostname & protocol for your site
# twitter_username: no_user
github_username:  DAlexis

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
